# Generated by Django 2.2 on 2022-01-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_auto_20220125_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
